package sql_test

import (
	"database/sql"
	"testing"

	_ "github.com/glebarez/sqlite"

	wctx "github.com/fabricatorsltd/go-wormhole/pkg/context"
	"github.com/fabricatorsltd/go-wormhole/pkg/schema"
	wsql "github.com/fabricatorsltd/go-wormhole/pkg/sql"
)

type cItem struct {
	ID    int `db:"column:id;primary_key;auto_increment"`
	Qty   int `db:"column:qty"`
	Price int `db:"column:price"`
	Total int `db:"column:total;computed"` // total = qty * price, generated by the DB
}

func openComputedDB(t *testing.T) *sql.DB {
	t.Helper()
	db, err := sql.Open("sqlite", "file::memory:?cache=shared")
	if err != nil {
		t.Fatal(err)
	}
	db.SetMaxOpenConns(1)
	if _, err := db.Exec(`CREATE TABLE "c_item" (
		"id" INTEGER PRIMARY KEY AUTOINCREMENT,
		"qty" INTEGER NOT NULL,
		"price" INTEGER NOT NULL,
		"total" INTEGER GENERATED ALWAYS AS ("qty" * "price") STORED)`); err != nil {
		t.Fatal(err)
	}
	return db
}

// Insert omits the computed column (writing it would make SQLite reject the
// statement), and a later Find reads the DB-generated value.
func TestE2E_Computed_InsertAndReadBack(t *testing.T) {
	db := openComputedDB(t)
	defer db.Close()
	ctx := wctx.New(wsql.New(db))
	defer ctx.Close()

	it := &cItem{Qty: 3, Price: 10}
	ctx.Add(it)
	if err := ctx.Save(); err != nil {
		t.Fatalf("save insert (computed column not excluded?): %v", err)
	}

	read := wctx.New(wsql.New(db))
	defer read.Close()
	var got cItem
	if err := read.Set(&got).Find(it.ID); err != nil {
		t.Fatal(err)
	}
	if got.Total != 30 {
		t.Errorf("computed total read back: got %d, want 30", got.Total)
	}
}

// Mutating only the computed field must produce no UPDATE (a no-op), not a
// database error from writing a generated column. This is the gate test: with
// change-detection skipping computed, Save does nothing; without it, the emitted
// UPDATE would be rejected.
func TestE2E_Computed_MutationIsNoOp(t *testing.T) {
	db := openComputedDB(t)
	defer db.Close()
	if _, err := db.Exec(`INSERT INTO "c_item" ("qty","price") VALUES (3,10)`); err != nil {
		t.Fatal(err)
	}
	ctx := wctx.New(wsql.New(db))
	defer ctx.Close()

	var it cItem
	if err := ctx.Set(&it).Find(1); err != nil {
		t.Fatal(err)
	}
	it.Total = 999 // attempt to write the computed column
	if err := ctx.Save(); err != nil {
		t.Fatalf("save with only a computed-field change should be a no-op, got: %v", err)
	}
	var total int
	if err := db.QueryRow(`SELECT "total" FROM "c_item" WHERE "id"=1`).Scan(&total); err != nil {
		t.Fatal(err)
	}
	if total != 30 {
		t.Errorf("computed total in DB: got %d, want 30 (unchanged)", total)
	}
}

// A real field change still updates and the DB recomputes the column.
func TestE2E_Computed_RealUpdateRecomputes(t *testing.T) {
	db := openComputedDB(t)
	defer db.Close()
	if _, err := db.Exec(`INSERT INTO "c_item" ("qty","price") VALUES (3,10)`); err != nil {
		t.Fatal(err)
	}
	ctx := wctx.New(wsql.New(db))
	defer ctx.Close()

	var it cItem
	if err := ctx.Set(&it).Find(1); err != nil {
		t.Fatal(err)
	}
	it.Qty = 5
	if err := ctx.Save(); err != nil {
		t.Fatalf("save: %v", err)
	}
	var total int
	if err := db.QueryRow(`SELECT "total" FROM "c_item" WHERE "id"=1`).Scan(&total); err != nil {
		t.Fatal(err)
	}
	if total != 50 {
		t.Errorf("recomputed total: got %d, want 50", total)
	}
}

func init() {
	schema.Parse(&cItem{})
}
