// Command modeling shows the mapping features beyond a flat table: composite
// primary keys, database-computed columns, a value object stored as JSON, and
// a single-table hierarchy split by a discriminator column.
//
//	go run ./examples/modeling
package main

import (
	"database/sql"
	"errors"
	"fmt"
	"log"

	_ "github.com/glebarez/sqlite"

	wh "github.com/fabricatorsltd/go-wormhole/pkg/context"
	"github.com/fabricatorsltd/go-wormhole/pkg/dsl"
	wsql "github.com/fabricatorsltd/go-wormhole/pkg/sql"
)

// OrderLine has a two-column primary key (order_id, line_no).
type OrderLine struct {
	OrderID int    `db:"column:order_id;primary_key"`
	LineNo  int    `db:"column:line_no;primary_key"`
	Product string `db:"column:product"`
	Qty     int    `db:"column:qty"`
}

// Invoice.Total is generated by the database. The computed tag keeps it out of
// INSERT and UPDATE statements.
type Invoice struct {
	ID    int `db:"column:id;primary_key"`
	Qty   int `db:"column:qty"`
	Price int `db:"column:price"`
	Total int `db:"column:total;computed"`
}

// Address is a value object with no table of its own.
type Address struct {
	Street string `json:"street"`
	City   string `json:"city"`
}

// Profile stores its Address as a single JSON column.
type Profile struct {
	ID      int     `db:"column:id;primary_key"`
	Name    string  `db:"column:name"`
	Address Address `db:"column:address;json"`
}

// Geo is an owned value object flattened into its owner's columns.
type Geo struct {
	Lat float64 `db:"column:lat"`
	Lng float64 `db:"column:lng"`
}

// Shipment owns two Geo points. Each is flattened into the shipment table under
// its own column prefix: origin_lat, origin_lng, dest_lat, dest_lng.
type Shipment struct {
	ID     int `db:"column:id;primary_key"`
	Origin Geo `db:"owned;prefix:origin_"`
	Dest   Geo `db:"owned;prefix:dest_"`
}

// CardPayment and WirePayment share the "payment" table. The kind column is the
// discriminator; each type owns one value of it.
type CardPayment struct {
	ID     int    `db:"column:id;primary_key;table:payment"`
	Kind   string `db:"column:kind;discriminator:card"`
	Amount int    `db:"column:amount"`
	Last4  string `db:"column:last4"`
}

type WirePayment struct {
	ID     int    `db:"column:id;primary_key;table:payment"`
	Kind   string `db:"column:kind;discriminator:wire"`
	Amount int    `db:"column:amount"`
	Bank   string `db:"column:bank"`
}

func init() {
	dsl.Register(OrderLine{})
	dsl.Register(Invoice{})
	dsl.Register(Profile{})
	dsl.Register(Shipment{})
	dsl.Register(CardPayment{})
	dsl.Register(WirePayment{})
}

func main() {
	db := open()
	defer db.Close()

	ctx := wh.New(wsql.New(db))
	defer ctx.Close()

	compositeKeys(ctx)
	computedColumn(ctx)
	jsonValueObject(ctx)
	ownedValueObject(ctx)
	singleTableHierarchy(ctx)
}

func compositeKeys(ctx *wh.DbContext) {
	ctx.Add(
		&OrderLine{OrderID: 100, LineNo: 1, Product: "widget", Qty: 3},
		&OrderLine{OrderID: 100, LineNo: 2, Product: "gadget", Qty: 1},
	)
	must(ctx.Save())

	// Find takes the key parts in declaration order: (order_id, line_no).
	var line OrderLine
	must(ctx.Set(&line).Find(100, 2))
	fmt.Printf("composite key: order 100 line 2 is %q\n", line.Product)
}

func computedColumn(ctx *wh.DbContext) {
	ctx.Add(&Invoice{ID: 1, Qty: 4, Price: 25}) // Total is left to the database
	must(ctx.Save())

	var inv Invoice
	must(ctx.Set(&inv).Find(1))
	fmt.Printf("computed column: %d x %d = %d\n", inv.Qty, inv.Price, inv.Total)
}

func jsonValueObject(ctx *wh.DbContext) {
	ctx.Add(&Profile{ID: 1, Name: "Ada", Address: Address{Street: "1 Loop", City: "Cupertino"}})
	must(ctx.Save())

	var p Profile
	must(ctx.Set(&p).Find(1))
	fmt.Printf("json value object: %s lives in %s\n", p.Name, p.Address.City)
}

func ownedValueObject(ctx *wh.DbContext) {
	ctx.Add(&Shipment{
		ID:     1,
		Origin: Geo{Lat: 37.77, Lng: -122.42},
		Dest:   Geo{Lat: 40.71, Lng: -74.01},
	})
	must(ctx.Save())

	var s Shipment
	must(ctx.Set(&s).Find(1))
	fmt.Printf("owned value object: origin (%.2f, %.2f) -> dest (%.2f, %.2f)\n",
		s.Origin.Lat, s.Origin.Lng, s.Dest.Lat, s.Dest.Lng)
}

func singleTableHierarchy(ctx *wh.DbContext) {
	// Both subtypes write to "payment"; the discriminator is set by the mapping.
	ctx.Add(
		&CardPayment{ID: 1, Amount: 50, Last4: "4242"},
		&WirePayment{ID: 2, Amount: 900, Bank: "Acme"},
	)
	must(ctx.Save())

	// A query for one subtype sees only its own rows.
	var cards []CardPayment
	must(ctx.Set(&cards).All())
	fmt.Printf("single-table hierarchy: %d card row(s), ", len(cards))

	var wires []WirePayment
	must(ctx.Set(&wires).All())
	fmt.Printf("%d wire row(s)\n", len(wires))

	// The wire row is invisible to a CardPayment lookup, even by its key.
	var miss CardPayment
	if err := ctx.Set(&miss).Find(2); errors.Is(err, sql.ErrNoRows) {
		fmt.Println("discriminator isolation: wire row not findable as a card")
	}
}

func open() *sql.DB {
	db, err := sql.Open("sqlite", ":memory:")
	must(err)
	db.SetMaxOpenConns(1)
	_, err = db.Exec(`
		CREATE TABLE "order_line" (
			"order_id" INTEGER NOT NULL,
			"line_no"  INTEGER NOT NULL,
			"product"  TEXT NOT NULL,
			"qty"      INTEGER NOT NULL,
			PRIMARY KEY ("order_id", "line_no"));
		CREATE TABLE "invoice" (
			"id"    INTEGER PRIMARY KEY,
			"qty"   INTEGER NOT NULL,
			"price" INTEGER NOT NULL,
			"total" INTEGER GENERATED ALWAYS AS ("qty" * "price") VIRTUAL);
		CREATE TABLE "profile" (
			"id"      INTEGER PRIMARY KEY,
			"name"    TEXT NOT NULL,
			"address" TEXT NOT NULL);
		CREATE TABLE "shipment" (
			"id"         INTEGER PRIMARY KEY,
			"origin_lat" REAL NOT NULL,
			"origin_lng" REAL NOT NULL,
			"dest_lat"   REAL NOT NULL,
			"dest_lng"   REAL NOT NULL);
		CREATE TABLE "payment" (
			"id"     INTEGER PRIMARY KEY,
			"kind"   TEXT NOT NULL,
			"amount" INTEGER NOT NULL,
			"last4"  TEXT,
			"bank"   TEXT);`)
	must(err)
	return db
}

func must(err error) {
	if err != nil {
		log.Fatal(err)
	}
}
