package migrations

import (
	"fmt"
	"strings"
	"time"

	"github.com/fabricatorsltd/go-wormhole/pkg/migrations/util"
)

// GenerateMigrationFile produces the Go source code for a timestamped
// migration file with Up() and Down() methods, pre-populated from
// the diff operations.
func GenerateMigrationFile(name string, ops []MigrationOp) string {
	ts := time.Now().UTC().Format("20060102150405")
	migrationID := ts + "_" + util.ToSnake(name)

	var up strings.Builder
	var down strings.Builder

	for _, op := range ops {
		writeUpOp(&up, op)
		writeDownOp(&down, op)
	}

	return fmt.Sprintf(`package migrations

import "github.com/fabricatorsltd/go-wormhole/pkg/migrations"

func init() {
	Register(migrations.Migration{
		ID: %q,
		Up: func(b *migrations.SchemaBuilder) {
%s		},
		Down: func(b *migrations.SchemaBuilder) {
%s		},
	})
}
`, migrationID, up.String(), down.String())
}

// MigrationFileName returns the file name for a migration.
func MigrationFileName(name string) string {
	ts := time.Now().UTC().Format("20060102150405")
	return ts + "_" + util.ToSnake(name) + ".go"
}

// SQLScriptFileName returns a .sql file name for a migration.
func SQLScriptFileName(name string) string {
	ts := time.Now().UTC().Format("20060102150405")
	return ts + "_" + util.ToSnake(name) + ".sql"
}

// GenerateSQLScript renders migration ops as a plain SQL script using
// the given dialect. Each statement is terminated with ";\n".
func GenerateSQLScript(ops []MigrationOp, dialect Dialect) string {
	if dialect == nil {
		dialect = DefaultDialect{}
	}
	b := NewBuilderWith(dialect)
	for _, op := range ops {
		b.ops = append(b.ops, op)
	}
	stmts := b.Statements()

	var out strings.Builder
	out.WriteString("-- Auto-generated by wormhole migrations script\n")
	out.WriteString("-- Dialect: " + fmt.Sprintf("%T", dialect) + "\n\n")
	for _, s := range stmts {
		out.WriteString(s)
		if !strings.HasSuffix(s, ";") {
			out.WriteString(";")
		}
		out.WriteString("\n\n")
	}
	return out.String()
}

func writeUpOp(w *strings.Builder, op MigrationOp) {
	switch o := op.(type) {
	case CreateTableOp:
		w.WriteString(fmt.Sprintf("\t\t\tb.CreateTable(%q", o.Table))
		for _, c := range o.Columns {
			w.WriteString(",\n\t\t\t\t")
			writeColumnLiteral(w, c)
		}
		w.WriteString(",\n\t\t\t)\n")

	case DropTableOp:
		w.WriteString(fmt.Sprintf("\t\t\tb.DropTable(%q)\n", o.Table))

	case AddColumnOp:
		w.WriteString(fmt.Sprintf("\t\t\tb.AddColumn(%q, ", o.Table))
		writeColumnLiteral(w, o.Column)
		w.WriteString(")\n")

	case DropColumnOp:
		w.WriteString(fmt.Sprintf("\t\t\tb.DropColumn(%q, %q)\n", o.Table, o.Column))

	case AlterColumnOp:
		w.WriteString(fmt.Sprintf("\t\t\tb.AlterColumn(%q, ", o.Table))
		writeColumnLiteral(w, o.Column)
		w.WriteString(")\n")

	case CreateIndexOp:
		cols := make([]string, len(o.Columns))
		for i, c := range o.Columns {
			cols[i] = fmt.Sprintf("%q", c)
		}
		w.WriteString(fmt.Sprintf("\t\t\tb.CreateIndex(%q, %q, %v, %s)\n",
			o.Name, o.Table, o.Unique, strings.Join(cols, ", ")))

	case DropIndexOp:
		w.WriteString(fmt.Sprintf("\t\t\tb.DropIndex(%q)\n", o.Name))
	}
}

func writeDownOp(w *strings.Builder, op MigrationOp) {
	// Reverse operations
	switch o := op.(type) {
	case CreateTableOp:
		w.WriteString(fmt.Sprintf("\t\t\tb.DropTable(%q)\n", o.Table))

	case DropTableOp:
		// Cannot fully reverse a drop — generate placeholder
		w.WriteString(fmt.Sprintf("\t\t\t// TODO: recreate table %q\n", o.Table))

	case AddColumnOp:
		w.WriteString(fmt.Sprintf("\t\t\tb.DropColumn(%q, %q)\n", o.Table, o.Column.Name))

	case DropColumnOp:
		// Cannot fully reverse — placeholder
		w.WriteString(fmt.Sprintf("\t\t\t// TODO: re-add column %q to %q\n", o.Column, o.Table))

	case AlterColumnOp:
		w.WriteString(fmt.Sprintf("\t\t\t// TODO: revert column %q in %q\n", o.Column.Name, o.Table))

	case CreateIndexOp:
		w.WriteString(fmt.Sprintf("\t\t\tb.DropIndex(%q)\n", o.Name))

	case DropIndexOp:
		w.WriteString(fmt.Sprintf("\t\t\t// TODO: recreate index %q\n", o.Name))
	}
}

func writeColumnLiteral(w *strings.Builder, c ColumnDef) {
	w.WriteString("migrations.ColumnDef{")
	w.WriteString(fmt.Sprintf("Name: %q", c.Name))
	if c.SQLType != "" {
		w.WriteString(fmt.Sprintf(", SQLType: %q", c.SQLType))
	}
	if c.PrimaryKey {
		w.WriteString(", PrimaryKey: true")
	}
	if c.AutoIncr {
		w.WriteString(", AutoIncr: true")
	}
	if c.Nullable {
		w.WriteString(", Nullable: true")
	}
	if c.Default != "" {
		w.WriteString(fmt.Sprintf(", Default: %q", c.Default))
	}
	w.WriteString("}")
}


