package migrations

import (
	"fmt"
	"strings"
)

// IdempotentScripter is an optional dialect capability: it wraps a migration's
// statements in a history-existence guard so the generated script can be re-run
// without re-applying. Only dialects with a procedural conditional outside a
// routine implement it (PostgreSQL via an anonymous DO block, SQL Server via a
// top-level IF). SQLite and MySQL have no such construct, so an idempotent
// script is not expressible for them and GenerateIdempotentSQLScript reports it
// rather than emitting one that would not guard.
//
// Procedural-wrapper caveats: a few statements cannot run inside the wrapper.
// PostgreSQL runs the DO body in one transaction, so CREATE INDEX CONCURRENTLY
// and VACUUM are rejected, and a RawSQLOp body containing "$$" breaks the
// dollar quoting. SQL Server requires CREATE PROCEDURE/VIEW/TRIGGER/FUNCTION to
// be first in a batch, so they cannot live inside the IF block. Such migrations
// should be applied through the runner rather than as an idempotent script.
type IdempotentScripter interface {
	// IdempotentHistoryDDL creates the history table if absent, so the script is
	// self-contained on a fresh database (it reads the table in its guard).
	IdempotentHistoryDDL(historyTable string) string
	// WrapIdempotent guards statements with a history-existence block and records
	// the migration inside it.
	WrapIdempotent(migrationID, historyTable string, statements []string) string
}

// idempotentScripter returns the dialect as an IdempotentScripter, or reports
// that the dialect cannot express a guarded block (SQLite, MySQL).
func idempotentScripter(dialect Dialect) (IdempotentScripter, error) {
	scr, ok := dialect.(IdempotentScripter)
	if !ok {
		return nil, fmt.Errorf("idempotent scripts are not supported for %T (no procedural IF outside a routine); generate a plain script and apply it through the runner instead", dialect)
	}
	return scr, nil
}

// GenerateIdempotentSQLScript renders a single migration's up operations as an
// idempotent SQL block: the statements and the history row are applied only when
// the migration is not already recorded. It returns an error for a dialect that
// cannot express the guard (SQLite, MySQL).
func GenerateIdempotentSQLScript(migrationID string, ops []MigrationOp, dialect Dialect) (string, error) {
	if dialect == nil {
		dialect = DefaultDialect{}
	}
	scr, err := idempotentScripter(dialect)
	if err != nil {
		return "", err
	}
	b := NewBuilderWith(dialect)
	for _, op := range ops {
		b.AddOp(op)
	}

	var out strings.Builder
	out.WriteString("-- Auto-generated by wormhole migrations script --idempotent\n")
	out.WriteString("-- Migration: " + migrationID + "\n\n")
	out.WriteString(scr.IdempotentHistoryDDL(historyTable))
	out.WriteString("\n")
	out.WriteString(scr.WrapIdempotent(migrationID, historyTable, b.Statements()))
	return out.String(), nil
}

// ScriptFilesIdempotent renders every file-based migration in dir as a single
// self-contained idempotent script: the history table is created once at the
// top, then each migration is guarded by its own history check, in ID order. It
// returns an error for a dialect that cannot express the guard.
func ScriptFilesIdempotent(dir string, dialect Dialect) (string, error) {
	if dialect == nil {
		dialect = DefaultDialect{}
	}
	scr, err := idempotentScripter(dialect)
	if err != nil {
		return "", err
	}
	migs, err := LoadMigrationDir(dir)
	if err != nil {
		return "", err
	}
	var out strings.Builder
	out.WriteString("-- Auto-generated by wormhole migrations script --idempotent\n\n")
	out.WriteString(scr.IdempotentHistoryDDL(historyTable))
	out.WriteString("\n")
	for _, m := range migs {
		b := NewBuilderWith(dialect)
		for _, op := range m.Up {
			b.AddOp(op)
		}
		out.WriteString("-- " + m.ID + "\n")
		out.WriteString(scr.WrapIdempotent(m.ID, historyTable, b.Statements()))
		out.WriteString("\n")
	}
	return out.String(), nil
}

// ScriptMigrationsIdempotent renders registered (code) migrations as a single
// self-contained idempotent script. Registered migrations carry a build
// function rather than stored ops, so their statements are rendered first and
// then guarded.
func ScriptMigrationsIdempotent(migs []Migration, dialect Dialect) (string, error) {
	if dialect == nil {
		dialect = DefaultDialect{}
	}
	scr, err := idempotentScripter(dialect)
	if err != nil {
		return "", err
	}
	var out strings.Builder
	out.WriteString("-- Auto-generated by wormhole migrations script --idempotent\n\n")
	out.WriteString(scr.IdempotentHistoryDDL(historyTable))
	out.WriteString("\n")
	for _, m := range migs {
		b := NewBuilderWith(dialect)
		m.Up(b)
		out.WriteString("-- " + m.ID + "\n")
		out.WriteString(scr.WrapIdempotent(m.ID, historyTable, b.Statements()))
		out.WriteString("\n")
	}
	return out.String(), nil
}
