package migrations

import (
	"context"
	"database/sql"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// LoadedMigration is a migration decoded from its JSON manifest on disk.
type LoadedMigration struct {
	ID   string
	Up   []MigrationOp
	Down []MigrationOp
}

// LoadMigrationDir reads every migration manifest (*.json with a non-empty id)
// from dir and returns them sorted by ID. Non-migration JSON in the directory
// (e.g. the schema snapshot, which has no id) is skipped, so a standalone CLI
// can apply migrations without compiling the project.
func LoadMigrationDir(dir string) ([]LoadedMigration, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}

	var migs []LoadedMigration
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".json") {
			continue
		}
		data, err := os.ReadFile(filepath.Join(dir, e.Name()))
		if err != nil {
			return nil, err
		}
		id, up, down, err := UnmarshalMigration(data)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", e.Name(), err)
		}
		if id == "" {
			continue // not a migration manifest (e.g. the snapshot)
		}
		migs = append(migs, LoadedMigration{ID: id, Up: up, Down: down})
	}

	sort.Slice(migs, func(i, j int) bool { return migs[i].ID < migs[j].ID })
	return migs, nil
}

// PendingFiles returns the IDs of file-based migrations not yet applied.
func PendingFiles(ctx context.Context, db *sql.DB, dir string) ([]string, error) {
	if err := EnsureHistoryTable(ctx, db); err != nil {
		return nil, err
	}
	applied, err := AppliedMigrations(ctx, db)
	if err != nil {
		return nil, err
	}
	migs, err := LoadMigrationDir(dir)
	if err != nil {
		return nil, err
	}
	var pending []string
	for _, m := range migs {
		if !applied[m.ID] {
			pending = append(pending, m.ID)
		}
	}
	return pending, nil
}

// ApplyPendingFiles applies the not-yet-applied file-based migrations from dir,
// rendering each migration's operations with the given dialect (so the DDL
// matches the target database) and recording history. Each migration runs in
// its own transaction. Returns the IDs applied. No project compilation needed.
func ApplyPendingFiles(ctx context.Context, db *sql.DB, dialect Dialect, dir string) ([]string, error) {
	if dialect == nil {
		dialect = DefaultDialect{}
	}
	if err := EnsureHistoryTable(ctx, db); err != nil {
		return nil, err
	}
	applied, err := AppliedMigrations(ctx, db)
	if err != nil {
		return nil, err
	}
	migs, err := LoadMigrationDir(dir)
	if err != nil {
		return nil, err
	}

	var done []string
	for _, m := range migs {
		if applied[m.ID] {
			continue
		}
		b := NewBuilderWith(dialect)
		for _, op := range m.Up {
			b.AddOp(op)
		}

		tx, err := db.BeginTx(ctx, nil)
		if err != nil {
			return done, err
		}
		for _, stmt := range b.Statements() {
			if _, err := tx.ExecContext(ctx, stmt); err != nil {
				_ = tx.Rollback()
				return done, fmt.Errorf("migration %s: %w", m.ID, err)
			}
		}
		if err := RecordMigration(ctx, tx, m.ID, dialect); err != nil {
			_ = tx.Rollback()
			return done, fmt.Errorf("migration %s: record: %w", m.ID, err)
		}
		if err := tx.Commit(); err != nil {
			return done, fmt.Errorf("migration %s: commit: %w", m.ID, err)
		}
		done = append(done, m.ID)
	}
	return done, nil
}

// ScriptFiles renders the up operations of every file-based migration in dir as
// a cumulative SQL script for the dialect, in ID order.
func ScriptFiles(dir string, dialect Dialect) (string, error) {
	if dialect == nil {
		dialect = DefaultDialect{}
	}
	migs, err := LoadMigrationDir(dir)
	if err != nil {
		return "", err
	}

	var out strings.Builder
	out.WriteString("-- Auto-generated by wormhole migrations script\n\n")
	for _, m := range migs {
		b := NewBuilderWith(dialect)
		for _, op := range m.Up {
			b.AddOp(op)
		}
		out.WriteString("-- " + m.ID + "\n")
		for _, stmt := range b.Statements() {
			out.WriteString(stmt)
			if !strings.HasSuffix(stmt, ";") {
				out.WriteString(";")
			}
			out.WriteString("\n")
		}
		out.WriteString("\n")
	}
	return out.String(), nil
}

// ReverseOps computes a best-effort inverse of the given up operations for a
// migration's down manifest, in reverse order: CreateTable -> DropTable,
// AddColumn -> DropColumn, CreateIndex -> DropIndex. Operations whose inverse is
// not computable from the operation alone (DropTable, DropColumn, AlterColumn,
// DropIndex, RawSQL) are omitted, so a down is best-effort, not guaranteed to
// fully restore. Callers needing exact rollback should hand-write the down.
func ReverseOps(up []MigrationOp) []MigrationOp {
	var down []MigrationOp
	for i := len(up) - 1; i >= 0; i-- {
		switch o := up[i].(type) {
		case CreateTableOp:
			down = append(down, DropTableOp{Table: o.Table})
		case AddColumnOp:
			down = append(down, DropColumnOp{Table: o.Table, Column: o.Column.Name})
		case CreateIndexOp:
			down = append(down, DropIndexOp{Name: o.Name, Table: o.Table})
		}
	}
	return down
}
