package migrations

import (
	"encoding/json"
	"os"
	"sort"
	"strings"
)

// WriteSnapshot serializes a DatabaseSchema to a JSON model-snapshot file. It is
// the saved "current state" that the next `migrations add` diffs against, the
// way EF Core uses its ModelSnapshot. Each column's concrete SQLType is resolved
// before writing so the snapshot is self-contained (GoType is not serialized).
func WriteSnapshot(path string, schema DatabaseSchema) error {
	b, err := json.MarshalIndent(normalizeSchema(schema), "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, append(b, '\n'), 0o644)
}

// LoadSnapshot reads a snapshot written by WriteSnapshot. A missing file yields
// an empty schema (the first migration diffs against nothing), not an error.
func LoadSnapshot(path string) (DatabaseSchema, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return DatabaseSchema{Tables: map[string]*TableSchema{}}, nil
		}
		return DatabaseSchema{}, err
	}
	var s DatabaseSchema
	if err := json.Unmarshal(b, &s); err != nil {
		return DatabaseSchema{}, err
	}
	if s.Tables == nil {
		s.Tables = map[string]*TableSchema{}
	}
	return s, nil
}

// normalizeSchema returns a deep copy with every column's SQLType resolved to a
// concrete string and GoType cleared, so the serialized snapshot does not depend
// on runtime reflection types and diffs stay stable on reload.
func normalizeSchema(schema DatabaseSchema) DatabaseSchema {
	out := DatabaseSchema{Tables: make(map[string]*TableSchema, len(schema.Tables))}
	for name, ts := range schema.Tables {
		nt := &TableSchema{Name: ts.Name, Columns: make(map[string]*ColumnDef, len(ts.Columns))}
		for cn, c := range ts.Columns {
			cc := normalizeColumn(*c)
			nt.Columns[cn] = &cc
		}
		out.Tables[name] = nt
	}
	return out
}

// normalizeColumn resolves a column's concrete SQLType (so it does not depend on
// a runtime reflect.Type) and clears GoType, making it safe to serialize and
// stable to diff on reload. Columns that already carry a SQLType are unchanged.
func normalizeColumn(c ColumnDef) ColumnDef {
	if c.SQLType == "" && c.GoType != nil {
		c.SQLType = GoTypeToSQL(c.GoType)
	}
	c.GoType = nil
	return c
}

// ScriptMigrations renders the given migrations as a cumulative SQL script for
// the dialect, in ID order, mirroring EF Core's `migrations script` (which emits
// the SQL of existing migrations, not a model diff). A nil dialect uses the
// default.
func ScriptMigrations(migs []Migration, dialect Dialect) string {
	if dialect == nil {
		dialect = DefaultDialect{}
	}
	sorted := make([]Migration, len(migs))
	copy(sorted, migs)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].ID < sorted[j].ID })

	var out strings.Builder
	out.WriteString("-- Auto-generated by wormhole migrations script\n\n")
	for _, m := range sorted {
		if m.Up == nil {
			continue
		}
		b := NewBuilderWith(dialect)
		m.Up(b)
		out.WriteString("-- " + m.ID + "\n")
		for _, stmt := range b.Statements() {
			out.WriteString(stmt)
			if !strings.HasSuffix(stmt, ";") {
				out.WriteString(";")
			}
			out.WriteString("\n")
		}
		out.WriteString("\n")
	}
	return out.String()
}
